#!/usr/bin/env php

<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

(new \Rogierw\RwAcmeCli\Support\DotEnv(dirname(__FILE__), __DIR__ . '/.env'))->load();

$application = new \Rogierw\RwAcmeCli\ConsoleApplication;

$application->bootstrap();

$application->run();